name: "Build and deploy BananaHackers Store"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node-version: [22.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g gulp-cli
      - run: npm install
      - run: npm run build --if-present

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Package static files as artifacts
        uses: actions/upload-artifact@v4
        with:
          path: docs/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4